# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'exchange.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(40, 80, 226, 27))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.txt_para = QtWidgets.QLineEdit(self.widget)
        self.txt_para.setObjectName("txt_para")
        self.horizontalLayout.addWidget(self.txt_para)
        self.comboBox = QtWidgets.QComboBox(self.widget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(40, 150, 271, 18))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl_sonuc = QtWidgets.QLabel(self.widget1)
        self.lbl_sonuc.setObjectName("lbl_sonuc")
        self.horizontalLayout_2.addWidget(self.lbl_sonuc)
        self.lbl_tl = QtWidgets.QLabel(self.widget1)
        self.lbl_tl.setObjectName("lbl_tl")
        self.horizontalLayout_2.addWidget(self.lbl_tl)
        self.widget2 = QtWidgets.QWidget(self.centralwidget)
        self.widget2.setGeometry(QtCore.QRect(40, 40, 99, 101))
        self.widget2.setObjectName("widget2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_ana = QtWidgets.QLabel(self.widget2)
        self.lbl_ana.setObjectName("lbl_ana")
        self.verticalLayout.addWidget(self.lbl_ana)
        self.pushButton = QtWidgets.QPushButton(self.widget2)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Döviz Dönüştürücü"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Dolar"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Euro"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Sterlin"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Yuan"))
        self.lbl_sonuc.setText(_translate("MainWindow", "Sonuç:"))
        self.lbl_tl.setText(_translate("MainWindow", "₺"))
        self.lbl_ana.setText(_translate("MainWindow", "Para Dönüştür"))
        self.pushButton.setText(_translate("MainWindow", "Dönüştür"))
