# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'exchange.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_ana = QtWidgets.QLabel(self.centralwidget)
        self.lbl_ana.setGeometry(QtCore.QRect(40, 40, 141, 41))
        self.lbl_ana.setObjectName("lbl_ana")
        self.txt_para = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_para.setGeometry(QtCore.QRect(40, 80, 111, 21))
        self.txt_para.setObjectName("txt_para")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(170, 80, 104, 26))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.lbl_sonuc = QtWidgets.QLabel(self.centralwidget)
        self.lbl_sonuc.setGeometry(QtCore.QRect(40, 150, 111, 41))
        self.lbl_sonuc.setObjectName("lbl_sonuc")
        self.lbl_tl = QtWidgets.QLabel(self.centralwidget)
        self.lbl_tl.setGeometry(QtCore.QRect(180, 160, 71, 31))
        self.lbl_tl.setObjectName("lbl_tl")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(40, 110, 113, 32))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Döviz Dönüştürücü"))
        self.lbl_ana.setText(_translate("MainWindow", "Para Dönüştür"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Dolar"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Euro"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Sterlin"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Yuan"))
        self.lbl_sonuc.setText(_translate("MainWindow", "Sonuç:"))
        self.lbl_tl.setText(_translate("MainWindow", "₺"))
        self.pushButton.setText(_translate("MainWindow", "Dönüştür"))
